// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ09RuhoNmDKk6rO8ni7uzLmcS3NLF5Q0',
    appId: '1:630825608761:web:11e5073e5ad651e0fccfe8',
    messagingSenderId: '630825608761',
    projectId: 'flutterproject-d428e',
    authDomain: 'flutterproject-d428e.firebaseapp.com',
    databaseURL: 'https://flutterproject-d428e-default-rtdb.firebaseio.com',
    storageBucket: 'flutterproject-d428e.appspot.com',
    measurementId: 'G-RG366NG66X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_toPpTIWgBXr3Cu1rQy1hUsjYGnrCzSc',
    appId: '1:630825608761:android:c568ca8acfe5514dfccfe8',
    messagingSenderId: '630825608761',
    projectId: 'flutterproject-d428e',
    databaseURL: 'https://flutterproject-d428e-default-rtdb.firebaseio.com',
    storageBucket: 'flutterproject-d428e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaT0DRycl4DMXbPQz5YnpVWhcIbbv2qoY',
    appId: '1:630825608761:ios:29fe822d8ea4bc3bfccfe8',
    messagingSenderId: '630825608761',
    projectId: 'flutterproject-d428e',
    databaseURL: 'https://flutterproject-d428e-default-rtdb.firebaseio.com',
    storageBucket: 'flutterproject-d428e.appspot.com',
    iosClientId: '630825608761-u3sqh7frcuhsc85646vnmnri2pvlfq4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.dermalens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaT0DRycl4DMXbPQz5YnpVWhcIbbv2qoY',
    appId: '1:630825608761:ios:29fe822d8ea4bc3bfccfe8',
    messagingSenderId: '630825608761',
    projectId: 'flutterproject-d428e',
    databaseURL: 'https://flutterproject-d428e-default-rtdb.firebaseio.com',
    storageBucket: 'flutterproject-d428e.appspot.com',
    iosClientId: '630825608761-u3sqh7frcuhsc85646vnmnri2pvlfq4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.dermalens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ09RuhoNmDKk6rO8ni7uzLmcS3NLF5Q0',
    appId: '1:630825608761:web:deccb5c2f3d19f5dfccfe8',
    messagingSenderId: '630825608761',
    projectId: 'flutterproject-d428e',
    authDomain: 'flutterproject-d428e.firebaseapp.com',
    databaseURL: 'https://flutterproject-d428e-default-rtdb.firebaseio.com',
    storageBucket: 'flutterproject-d428e.appspot.com',
    measurementId: 'G-9WM0NMNL92',
  );
}
